services:
  db:
    container_name: conecta_ciudad_db_dev
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conecta_ciudad_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - conecta_ciudad_network

volumes:
  db_data:

networks:
  conecta_ciudad_network:
