package com.unimagdalena.conectaCiudad.enums;

public enum ErrorCode {
    
    REQUIRED_FIELD("REQUIRED_FIELD"),
    INVALID_DATE_RANGE("INVALID_DATE_RANGE"),
    INVALID_LENGTH("INVALID_LENGTH"),

    PROJECT_NOT_EDITABLE("PROJECT_NOT_EDITABLE"),
    PROJECT_NOT_SUBMITTABLE("PROJECT_NOT_SUBMITTABLE"),
    PROJECT_NOT_REVIEWABLE("PROJECT_NOT_REVIEWABLE"),
    PROJECT_START_DATE_TOO_SOON("PROJECT_START_DATE_TOO_SOON"),
    PROJECT_DATES_REQUIRED("PROJECT_DATES_REQUIRED"),
    PROJECT_END_BEFORE_START("PROJECT_END_BEFORE_START"),
    
    REVIEW_ALREADY_COMPLETED("REVIEW_ALREADY_COMPLETED"),
    REVIEW_OBSERVATIONS_TOO_SHORT("REVIEW_OBSERVATIONS_TOO_SHORT"),
    REVIEW_NOT_REVIEWABLE("REVIEW_NOT_REVIEWABLE"),
    REVIEW_NOT_APPROVABLE("REVIEW_NOT_APPROVABLE"),

    VOTING_DATES_REQUIRED("VOTING_DATES_REQUIRED"),
    VOTING_START_NOT_FUTURE("VOTING_START_NOT_FUTURE"),
    VOTING_END_BEFORE_START("VOTING_END_BEFORE_START"),
    VOTING_END_AFTER_PROJECT_START("VOTING_END_AFTER_PROJECT_START"),
    VOTING_BUFFER_TOO_SHORT("VOTING_BUFFER_TOO_SHORT"),
    VOTING_DURATION_TOO_SHORT("VOTING_DURATION_TOO_SHORT"),
    
    PASSWORD_REQUIRED("PASSWORD_REQUIRED"),
    PASSWORD_INCORRECT("PASSWORD_INCORRECT"),
    PASSWORD_TOO_SHORT("PASSWORD_TOO_SHORT"),
    PASSWORD_EMPTY("PASSWORD_EMPTY"),
    ROLE_CITIZEN_ONLY("ROLE_CITIZEN_ONLY"),
    EMAIL_AND_NATIONAL_ID_EXIST("EMAIL_AND_NATIONAL_ID_EXIST"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_INACTIVE("USER_INACTIVE"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    
    FILE_EMPTY("FILE_EMPTY"),
    FILE_INVALID_EXTENSION("FILE_INVALID_EXTENSION"),
    FILE_READ_ERROR("FILE_READ_ERROR"),
    
    CSV_EMPTY("CSV_EMPTY"),
    CSV_INVALID_HEADERS("CSV_INVALID_HEADERS"),
    CSV_READ_ERROR("CSV_READ_ERROR"),
    CSV_SAVE_ERROR("CSV_SAVE_ERROR"),
    CSV_FILE_TOO_LARGE("CSV_FILE_TOO_LARGE"),
    CSV_INSUFFICIENT_COLUMNS("CSV_INSUFFICIENT_COLUMNS"),
    CSV_COLUMN_MISMATCH("CSV_COLUMN_MISMATCH"),
    CSV_INVALID_FORMAT("CSV_INVALID_FORMAT"),
    CSV_DUPLICATE_EMAIL("CSV_DUPLICATE_EMAIL"),
    CSV_DUPLICATE_NATIONAL_ID("CSV_DUPLICATE_NATIONAL_ID"),
    CSV_EMAIL_EXISTS("CSV_EMAIL_EXISTS"),
    CSV_NATIONAL_ID_EXISTS("CSV_NATIONAL_ID_EXISTS"),
    CSV_FIELD_NAME_REQUIRED("CSV_FIELD_NAME_REQUIRED"),
    CSV_FIELD_EMAIL_REQUIRED("CSV_FIELD_EMAIL_REQUIRED"),
    CSV_FIELD_EMAIL_INVALID("CSV_FIELD_EMAIL_INVALID"),
    CSV_FIELD_NATIONAL_ID_REQUIRED("CSV_FIELD_NATIONAL_ID_REQUIRED"),
    CSV_FIELD_PHONE_REQUIRED("CSV_FIELD_PHONE_REQUIRED"),
    CSV_FIELD_PHONE_INVALID("CSV_FIELD_PHONE_INVALID"),
    CSV_FIELD_PASSWORD_REQUIRED("CSV_FIELD_PASSWORD_REQUIRED"),
    CSV_FIELD_PASSWORD_TOO_SHORT("CSV_FIELD_PASSWORD_TOO_SHORT"),
    
    ACTION_TYPE_REQUIRED("ACTION_TYPE_REQUIRED"),
    PROJECT_ID_REQUIRED("PROJECT_ID_REQUIRED"),
    DESCRIPTION_REQUIRED("DESCRIPTION_REQUIRED"),
    
    ROLE_NOT_FOUND("ROLE_NOT_FOUND"),
    PERMISSION_NOT_FOUND("PERMISSION_NOT_FOUND"),
    PERMISSION_ALREADY_ASSIGNED("PERMISSION_ALREADY_ASSIGNED"),
    PERMISSION_NOT_ASSIGNED("PERMISSION_NOT_ASSIGNED"),
    NO_VALID_PERMISSIONS("NO_VALID_PERMISSIONS"),
    
    INVALID_ROLE_FOR_OPERATION("INVALID_ROLE_FOR_OPERATION"),
    CANNOT_MODIFY_OWN_ROLE("CANNOT_MODIFY_OWN_ROLE"),
    CANNOT_DEACTIVATE_SELF("CANNOT_DEACTIVATE_SELF"),
    INVALID_USER_DATA("INVALID_USER_DATA"),
    DUPLICATE_EMAIL_AND_NATIONAL_ID("DUPLICATE_EMAIL_AND_NATIONAL_ID"),
    SYSTEM_USER_NOT_FOUND("SYSTEM_USER_NOT_FOUND"),
    
    ACCESS_DENIED_NOT_PROJECT_OWNER("ACCESS_DENIED_NOT_PROJECT_OWNER"),
    ACCESS_DENIED_NOT_ASSIGNED_CURATOR("ACCESS_DENIED_NOT_ASSIGNED_CURATOR"),
    
    UNKNOWN_ERROR("UNKNOWN_ERROR"),
    OPERATION_FAILED("OPERATION_FAILED");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
    
    @Override
    public String toString() {
        return code;
    }
}
