package com.unimagdalena.conectaCiudad.enums;

public enum ProjectActionType {
    CURATOR_ASSIGNED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    PROJECT_OBSERVATIONS_ADDED,
    PROJECT_APPROVED,
    PROJECT_SUBMITTED_FOR_REVIEW,
    CURATOR_REASSIGNED,
    PROJECT_STATUS_CHANGED
}
