package com.unimagdalena.conectaCiudad.enums;

public enum UserActionType {
    USER_CREATED,
    USER_PROFILE_UPDATED,
    USER_UPDATED,
    USER_PASSWORD_CHANGED,
    USER_DELETED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    USER_ROLE_ADDED,
    USER_ROLE_REMOVED,
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_BULK_IMPORT,
    USER_EXPORT,
    USER_ROLE_CHANGED,
    USER_PASSWORD_RESET,
    USER_STATUS_CHANGED,
    CITIZEN_VOTE
}
